all: server_ss client_ss server_ds client_ds

server_ds: server_ds.c
	gcc -Wall -g -o server_ds server_ds.c

client_ds: client_ds.c
	gcc -Wall -g -o client_ds client_ds.c

server_ss: server_ss.c
	gcc -Wall -g -o server_ss server_ss.c

client_ss: client_ss.c
	gcc -Wall -g -o client_ss client_ss.c
