all: mmapleser mmapschreiber

mmapleser: mmapleser.c
	gcc -Wall -g -o mmapleser mmapleser.c

mmapschreiber: mmapschreiber.c
	gcc -Wall -g -o mmapschreiber mmapschreiber.c

clean:
	rm *.o mmapleser mmapschreiber
