all: memory-reader memory-writer

memory-reader: memory-reader.c
	gcc -Wall -g -o memory-reader memory-reader.c

memory-writer: memory-writer.c
	gcc -Wall -g -o memory-writer memory-writer.c

clean:
	rm *.o memory-reader memory-writer
